# Generated by Django 4.2.3 on 2023-08-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lesson_5', '0002_advertisment_photo_advertisment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='photo',
            field=models.ImageField(upload_to='my_lesson_5', verbose_name='изображение'),
        ),
    ]
